// src/Background.tsx
import { useRef, useEffect } from 'react'

interface CanvasProps {
    width: number;
    height: number;
}

interface Arrow {
    x: number;
    y: number;
    dx: number;
    dy: number;
    size: number;
    color: string;
    transparency: number;
    rotation: number;
}

const debounce = (fn: Function, ms: number) => {
    let timer: number | undefined;

    return () => {
        clearTimeout(timer);
        timer = setTimeout(() => {
            timer = undefined;
            fn();
        }, ms);
    }
}

const Background = () => {

    const randomArrow = (ctx: CanvasRenderingContext2D) => {
        const width = ctx.canvas.width;
        const height = ctx.canvas.height;

        const dim = Math.min(width, height);

        const arrow = {
            x: 2*width * Math.random() - width,
            y: 2*height * Math.random() - height,
            dx: Math.random()*2-1,
            dy: Math.random()*2-1,
            size: Math.random()*dim/2+dim/3,
            color: `rgb(${Math.floor(142+Math.random()*142/2-142/4)}, ${Math.floor(36+Math.random()*18-9)}, ${Math.floor(170+Math.random()*170/2-170/4)})`,
            transparency: Math.random()*0.5+0.1,
            rotation: Math.floor(Math.random()*4)*Math.PI/2
        }

        return arrow;
    }

    const canvasRef = useRef<HTMLCanvasElement>(null);
    const requestIdRef = useRef<number|null>(null);
    const arrows = useRef<Array<Arrow>>([]);

    const drawArrow = (ctx: CanvasRenderingContext2D, arrow: Arrow) => {
        ctx.save();
        ctx.translate(arrow.x, arrow.y);
        ctx.scale(arrow.size/137, arrow.size/143);
        ctx.translate(137/2, 143/2);
        ctx.rotate(arrow.rotation);
        ctx.beginPath();

        const coords = [
            [0, 77],
            [11, 89],
            [79, 89],
            [48, 119],
            [48, 131],
            [59, 143],
            [72, 143],
            [137, 72],
            [137, 65],
            [72, 0],
            [59, 0],
            [48, 12],
            [48, 23],
            [79, 54],
            [11, 54]
        ];

        ctx.moveTo(-137/2, 66-143/2);
        coords.forEach((coord) => {
            ctx.lineTo(coord[0]-137/2, coord[1]-143/2);
        });

        ctx.fillStyle = arrow.color;
        ctx.globalAlpha = arrow.transparency;
        ctx.fill();

        ctx.closePath();
        ctx.restore();
    }

    const updateArrow = (ctx: CanvasRenderingContext2D, arrows: Array<Arrow>) => {
        const width = ctx.canvas.width;
        const height = ctx.canvas.height;

        for (var i = 0; i < arrows.length; i++) {
            const arrow = arrows[i];

            arrow.x += arrow.dx;
            arrow.y += arrow.dy;

            if (arrow.x <= -arrow.size || arrow.x > width || arrow.y <= -arrow.size || arrow.y > height) {
                const arrow = randomArrow(ctx);

                while (!(arrow.x <= -arrow.size || arrow.x > width || arrow.y <= -arrow.size || arrow.y > height)) {
                    arrow.x -= arrow.dx;
                    arrow.y -= arrow.dy;
                }

                arrows[i] = arrow;
            }
        }
    };

    const renderFrame = (ctx: CanvasRenderingContext2D) => {
        const width = ctx.canvas.width;
        const height = ctx.canvas.height;

        updateArrow(ctx, arrows.current);
        ctx.clearRect(0, 0, width, height);
        arrows.current.forEach((arrow) => drawArrow(ctx, arrow));
    };

    const tick = () => {
        const ctx = canvasRef.current?.getContext('2d');
        if (!ctx) return;

        renderFrame(ctx);

        requestIdRef.current = requestAnimationFrame(tick);
    };

    useEffect(() => {
        const ctx = canvasRef.current?.getContext('2d');
        if (!ctx) return;

        const handleResize = () => {
            ctx.canvas.height = window.innerHeight;
            ctx.canvas.width = window.innerWidth;

            arrows.current = Array.from({ length: 20 }, () => randomArrow(ctx));
        }

        arrows.current = Array.from({ length: 20 }, () => randomArrow(ctx));
        requestIdRef.current = requestAnimationFrame(tick);
        handleResize();
        window.addEventListener("resize", handleResize);

        return () => {
            window.removeEventListener("resize", handleResize);
            const requestId = requestIdRef.current;
            if (!requestId) return;

            cancelAnimationFrame(requestId);
        };
    }, []);

    return <canvas className="blur-sm h-full w-full" ref={canvasRef} />;
}

export default Background;

// client/src/lib/Background.svelte
<script lang='ts'>
	import { onMount } from 'svelte';
    import { drawArrow, randomArrow, updateArrow } from './arrows.js'
    import type { Arrow } from './arrows'

    let canvas: HTMLCanvasElement;
    let ctx: CanvasRenderingContext2D;
    let frameHandle: number;
    let arrows: Array<Arrow> = [];

    function handleResize() {
        ctx.canvas.height = window.innerHeight;
        ctx.canvas.width = window.innerWidth;

        arrows = Array.from({ length: 20 }, () => randomArrow(ctx));
    };

    function render() {
        if (!arrows.length) handleResize();
        
        updateArrow(ctx, arrows);
        ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
        arrows.forEach((arrow) => drawArrow(ctx, arrow));
    }

    onMount(() => {
        (function loop() {
            ctx = canvas.getContext('2d')!!;

            render();

            frameHandle = requestAnimationFrame(loop);
        })();

        return () => {
            cancelAnimationFrame(frameHandle)
        };
    });
</script>

<div class="absolute x-0 y-0 w-full h-full bg-gray-900 -z-50">
    <canvas bind:this={canvas} />
</div>
<svelte:window on:resize|passive={handleResize}/>
